### ISSUE TITLE
undefined symbol errors on libnacl 1.7

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/libnacl#117]
On debian 8, when upgrading to 1.7 I see this error:

```
ImportError: Failed to import test module: unit.modules.test_nacl
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/unit/modules/test_nacl.py", line 10, in <module>
    import salt.modules.nacl as nacl
  File "/tmp/kitchen/testing/salt/modules/nacl.py", line 157, in <module>
    import salt.utils.nacl
  File "/tmp/kitchen/testing/salt/utils/nacl.py", line 26, in <module>
    import libnacl.secret
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/local/lib/python2.7/site-packages/libnacl/__init__.py", line 166, in <module>
    randombytes_SEEDBYTES = nacl.randombytes_seedbytes()
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libsodium.so: undefined symbol: randombytes_seedbytes
```

This is because `randombytes_seedbytes` was added here https://github.com/jedisct1/libsodium/commit/cafb0a695b6a59ccc84e9718507e2f67f0810064  which was added to libsodium version 1.0.12 and by default it runs `libsodium18:amd64                1.0.8-5`

I'm also seeing this error on amazon linux 1 for similar reasons:

```
ImportError: Failed to import test module: integration.runners.test_nacl
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/integration/runners/test_nacl.py", line 15, in <module>
    import libnacl.secret  # pylint: disable=unused-import
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/local/lib/python2.7/site-packages/libnacl/__init__.py", line 126, in <module>
    crypto_box_SEEDBYTES = nacl.crypto_box_seedbytes()
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 374, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 379, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib64/libsodium.so.4: undefined symbol: crypto_box_seedbytes
```

ping @thatch45 should we just add this to a try/except or update docs for libsodium version requirements? im willing to put a PR together, just not sure the correct approach here.

**Comment by thatch45** [comment]
Yes, the right thing to do is add a try/except
