### ISSUE TITLE
unittest: ERROR: test_save_load (unit.test_save.TestSave.test_save_load) - TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by vt-alt** [saltstack/libnacl#136]
JSON unit tests fail on python 3.11.4;
```
======================================================================
ERROR: test_save_load (unit.test_save.TestSave.test_save_load)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/RPM/BUILD/python3-module-libnacl-1.7.1/tests/unit/test_save.py", line 32, in test_save_load
    bob_load = libnacl.utils.load_key(bob_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/RPM/BUILD/python3-module-libnacl-1.7.1/libnacl/utils.py", line 34, in load_key
    key_data = json.loads(stream.read(), encoding='UTF-8')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

======================================================================
ERROR: test_save_load_secret (unit.test_save.TestSave.test_save_load_secret)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/RPM/BUILD/python3-module-libnacl-1.7.1/tests/unit/test_save.py", line 63, in test_save_load_secret
    lbox = libnacl.utils.load_key(box_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/RPM/BUILD/python3-module-libnacl-1.7.1/libnacl/utils.py", line 34, in load_key
    key_data = json.loads(stream.read(), encoding='UTF-8')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

======================================================================
ERROR: test_save_load_sign (unit.test_save.TestSave.test_save_load_sign)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/RPM/BUILD/python3-module-libnacl-1.7.1/tests/unit/test_save.py", line 74, in test_save_load_sign
    signer_load = libnacl.utils.load_key(sign_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/RPM/BUILD/python3-module-libnacl-1.7.1/libnacl/utils.py", line 34, in load_key
    key_data = json.loads(stream.read(), encoding='UTF-8')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

----------------------------------------------------------------------
Ran 65 tests in 0.040s

FAILED (errors=3)
error: Bad exit status from /usr/src/tmp/rpm-tmp.12559 (%check)
````
It seems that `encoding` is removed since 3.9: https://docs.python.org/3/library/json.html#json.loads

> Changed in version 3.9: The keyword argument encoding has been removed.

**Comment by vt-alt** [comment]
Ah, excuse me, you seems fixed this already. I was testing for version 1.7.1 (from ALT Linux) which is quite old.
