### ISSUE TITLE
crypto_scalarmult_base can segfault

### ISSUE THREAD

**Issue by oconnor663** [saltstack/libnacl#75]
```
$ python
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libnacl
>>> libnacl.crypto_scalarmult_base(None)
Segmentation fault (core dumped)
```

This came up in https://github.com/keybase/saltpack-python/issues/1.

**Comment by oconnor663** [comment]
Compare to PyNaCl:

```
>>> import nacl.bindings
>>> nacl.bindings.crypto_scalarmult_base(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tmp.shr7Aj2HnY/lib/python3.5/site-packages/nacl/bindings/crypto_scalarmult.py", line 34, in crypto_scalarmult_base
    rc = lib.crypto_scalarmult_base(q, n)
TypeError: initializer for ctype 'unsigned char *' must be a cdata pointer, not NoneType
```

**Comment by thatch45** [comment]
wow, sorry I missed this, I will get this fixed!
